title: Xiao Hang
description: data kstream/web develop/Speech signal and machine learning

url: https://xiaohanghang.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: contact
   url: /contact

social:
   github: xiaohanghang
   email: hang3.liu@gmail.com

google_analytics: "UA-58263416-1"
